module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  auto_username: 0
  autologout: 0
  autosave_form: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  consumers: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  encrypt: 0
  entity_embed: 0
  facets: 0
  facets_rest: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  flag_bookmark: 0
  flippy: 0
  fontawesome: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_captcha: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonapi: 0
  key: 0
  layout_builder: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  login_onlyemail: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  moderated_content_bulk_publish: 0
  moderation_dashboard: 0
  moderation_sidebar: 0
  node: 0
  openapi: 0
  openapi_jsonapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  options: 0
  page_cache: 0
  page_manager: 0
  panels: 0
  path: 0
  path_alias: 0
  phpmailer_smtp: 0
  quickedit: 0
  rdf: 0
  realname: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  registration_role: 0
  rest: 0
  schemata: 0
  schemata_json_schema: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_db_defaults: 0
  seckit: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_oauth: 0
  smtp: 0
  superfish: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  tokenuuid: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_content_creator: 0
  webform_encrypt: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  covid19demo: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
